---
title: "Untitled"
author: "a"
date: '6 февраля 2018 г '
output: html_document
---

```{r}
library(tidyverse)
```
```{r}
library(irr)
```



```{r}
df <-  read.csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/Lera-Z/hw1_agreement/hw1_1_zilo_class.csv", stringsAsFactors = F, encoding = "UTF-8")
```



```{r}
df %>%
  distinct(stimulus_source, w_id) %>%
  count(stimulus_source) %>%
  as_tibble()
```



```{r}
df %>% 
  select(s_id, stimulus, translation_ru, stimulus_source, class) %>% 
  spread(key = s_id, value = class) ->
  classes
```




```{r}
agree(classes[,-c(1:3)])
```



```{r}
kappa2(classes[,-c(1:3)][,c(7, 11)])
```


```{r}
kappam.fleiss(classes[,-c(1:3)])
```



```{r}
df2 <- read.csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/Lera-Z/hw1_agreement/hw1_2_verbs.csv", stringsAsFactors = F, encoding = "UTF-8")
```


```{r}
df2 %>%
  distinct(SubjectCode) %>%
  count()# %>%
  #as_tibble()
```


```{r}
length(unique(df2$SubjectCode))
```


```{r}
df2 %>%
  group_by(WordType, Gender) %>%
  summarise(mean = mean(GivenScore))
```






